# Data for charts

In [1]:
import pandas as pd
import pickle
from datetime import datetime
from tqdm import tqdm
import json

In [7]:
users = pd.read_csv('users.csv')

In [8]:
users

,id,name,location,estimated_age,experiences,skills,school_1,school_2
0,ACoAAA_dS7gB-ucqa7BZwzbO1-kVxInduE2bsOg,Roberto Enrique Chavez Rodriguez,"Buenos Aires, Buenos Aires Province, Argentina",35.0,"[{'start_date': '2022-01-14', 'end_date': '202...","['JavaScript', 'Liquibase Community Edition', ...",Innopolis University,Innopolis University
1,ACoAAA_XHtcBA0rpWCcoM3yhkMOy04zzSKnd804,Maxim Shalavin,"Tbilisi, Georgia",34.0,"[{'start_date': '2023-04-14', 'end_date': None...","['Java', 'Android Development', 'Docker', 'Doc...",Innopolis University,Siberian State University of Telecommunication...
2,ACoAAA-ECYcB5_w3-SWAt3dPl2KOOSo7kA9NyfI,Olga Z.,"Kazan, Tatarstan, Russia",37.0,"[{'start_date': '2023-05-14', 'end_date': None...","['English', 'Translation Eng<->Rus', 'Graduate...",Tomsk Polytechnic University,Tomsk State University
3,ACoAAA00XfsBNdzmLH9mWWzP5jgdk-nu0YdDFRo,Timur Fazullin,"Innopolis, Tatarstan, Russia",40.0,"[{'start_date': '2024-10-14', 'end_date': None...","['Content marketing', 'Content management', 'C...",XYZ,Skillbox
4,ACoAAA0ImOkB2Ninxe_GudoAdBSx1Lt0sKb4R5g,Vasilii Zorin,"Toronto, Ontario, Canada",31.0,"[{'start_date': '2023-11-14', 'end_date': None...","['Scrum', 'Lean Software Development', 'Data A...",National University of Singapore,Innopolis University
...,...,...,...,...,...,...,...,...
2136,373,Student 373,no location,NaN,"[{'start_date': '2020-11-04', 'end_date': None...",[],Innopolis University,no
2137,374,Student 374,no location,NaN,"[{'start_date': '2021-07-04', 'end_date': None...",[],Innopolis University,no
2138,375,Student 375,no location,NaN,"[{'start_date': '2020-11-20', 'end_date': None...",[],Innopolis University,no
2139,376,Student 376,no location,NaN,"[{'start_date': '2019-05-01', 'end_date': None...",[],Innopolis University,no
2140,377,Student 377,no location,NaN,"[{'start_date': '2019-06-03', 'end_date': None...",[],Innopolis University,no

In [165]:
import ast

# Create list for users experiences
users_experiences = []

# Go through users['experiences'] to convert it in proper format
for experiences in users['experiences']:
    # If experience is empty, then skip it
    if len(experiences) == 0:
        users_experiences.append([])
        continue
    # Convert the string to a list
    data_list = ast.literal_eval(experiences)
    users_experiences.append(data_list)

In [166]:
# Load the mapping to categories
with open("job_categories_map.pkl", "rb") as f:
    job_categories_map = pickle.load(f)

## Chart for professions

In [ ]:
# Create map to store number of people in each category
job_categories = {'Software Engineering': 0,
                  'Data & Analytics': 0,
                  'Infrastructure & Networks': 0,
                  'Cloud & DevOps': 0,
                  'Cybersecurity': 0,
                  'Machine Learning & AI': 0,
                  'Product & Project Management': 0,
                  'IT Support & Administration': 0,
                  'UI/UX & Design': 0,
                  'Other': 0}

In [ ]:
users_experiences[0]

[{'start_date': '2022-01-14',
  'end_date': '2023-07-14',
  'title': 'Java Software Developer',
  'company': 'Innopolis University',
  'duration': 18},
 {'start_date': '2016-06-14',
  'end_date': '2016-10-14',
  'title': 'Energy Engineer',
  'company': 'Tech Mahindra',
  'duration': 4},
 {'start_date': '2015-05-14',
  'end_date': '2016-05-14',
  'title': 'Mechanical Engineer',
  'company': 'FINILAGER S.A.',
  'duration': 12},
 {'start_date': '2012-02-14',
  'end_date': '2014-12-14',
  'title': 'Graduate Teaching Assistant',
  'company': 'Universidad Mayor de San Andres',
  'duration': 34},
 {'start_date': '2013-08-14',
  'end_date': '2013-12-14',
  'title': 'Mechanical Engineer',
  'company': 'FCM Bolivia',
  'duration': 4},
 {'start_date': '2013-08-14',
  'end_date': '2013-09-14',
  'title': 'Translator and Logistics coordinator',
  'company': 'Suma Huasij – NGO to help community',
  'duration': 1},
 {'start_date': '2013-01-14',
  'end_date': '2013-07-14',
  'title': 'Volunteer',
  'company': 'Vamos Juntos Bolivia',
  'duration': 6},
 {'start_date': '2012-01-14',
  'end_date': '2012-02-14',
  'title': 'Mechanic Technician',
  'company': 'Inesco S.A',
  'duration': 1}]

In [ ]:
professions = {}

In [ ]:
# Iterate over users_experiences
for experiences in tqdm(users_experiences, total=users.shape[0]):
    for experience in experiences:
        # Extract start and end dates of working
        start_date = pd.to_datetime(experience['start_date']) if experience['start_date'] else pd.to_datetime(datetime.today())
        end_date = pd.to_datetime(experience['end_date']) if experience['end_date'] else pd.to_datetime(datetime.today())

        # Go through the interval from the start year to the end year and change the desired one
        for year in range(max(start_date.year, 2012), end_date.year + 1):
            category = job_categories_map[experience['title']]
            if year not in professions:
                professions[year] = job_categories.copy()
            professions[year][category] += 1

100%|██████████| 2141/2141 [00:07<00:00, 295.20it/s]

In [ ]:
professions

{2022: {'Software Engineering': 1472,
  'Data & Analytics': 164,
  'Infrastructure & Networks': 9,
  'Cloud & DevOps': 152,
  'Cybersecurity': 32,
  'Machine Learning & AI': 120,
  'Product & Project Management': 247,
  'IT Support & Administration': 340,
  'UI/UX & Design': 211,
  'Other': 214},
 2023: {'Software Engineering': 1439,
  'Data & Analytics': 160,
  'Infrastructure & Networks': 11,
  'Cloud & DevOps': 169,
  'Cybersecurity': 39,
  'Machine Learning & AI': 147,
  'Product & Project Management': 251,
  'IT Support & Administration': 337,
  'UI/UX & Design': 197,
  'Other': 215},
 2016: {'Software Engineering': 336,
  'Data & Analytics': 19,
  'Infrastructure & Networks': 1,
  'Cloud & DevOps': 35,
  'Cybersecurity': 16,
  'Machine Learning & AI': 16,
  'Product & Project Management': 106,
  'IT Support & Administration': 213,
  'UI/UX & Design': 70,
  'Other': 107},
 2015: {'Software Engineering': 260,
  'Data & Analytics': 14,
  'Infrastructure & Networks': 3,
  'Cloud & DevOps': 23,
  'Cybersecurity': 16,
  'Machine Learning & AI': 11,
  'Product & Project Management': 88,
  'IT Support & Administration': 211,
  'UI/UX & Design': 56,
  'Other': 98},
 2012: {'Software Engineering': 147,
  'Data & Analytics': 14,
  'Infrastructure & Networks': 1,
  'Cloud & DevOps': 12,
  'Cybersecurity': 8,
  'Machine Learning & AI': 5,
  'Product & Project Management': 59,
  'IT Support & Administration': 135,
  'UI/UX & Design': 24,
  'Other': 63},
 2013: {'Software Engineering': 177,
  'Data & Analytics': 16,
  'Infrastructure & Networks': 1,
  'Cloud & DevOps': 18,
  'Cybersecurity': 9,
  'Machine Learning & AI': 8,
  'Product & Project Management': 73,
  'IT Support & Administration': 156,
  'UI/UX & Design': 33,
  'Other': 76},
 2014: {'Software Engineering': 218,
  'Data & Analytics': 17,
  'Infrastructure & Networks': 2,
  'Cloud & DevOps': 18,
  'Cybersecurity': 12,
  'Machine Learning & AI': 7,
  'Product & Project Management': 78,
  'IT Support & Administration': 174,
  'UI/UX & Design': 45,
  'Other': 96},
 2024: {'Software Engineering': 1404,
  'Data & Analytics': 153,
  'Infrastructure & Networks': 9,
  'Cloud & DevOps': 152,
  'Cybersecurity': 41,
  'Machine Learning & AI': 135,
  'Product & Project Management': 236,
  'IT Support & Administration': 330,
  'UI/UX & Design': 183,
  'Other': 201},
 2025: {'Software Engineering': 1128,
  'Data & Analytics': 118,
  'Infrastructure & Networks': 8,
  'Cloud & DevOps': 118,
  'Cybersecurity': 33,
  'Machine Learning & AI': 98,
  'Product & Project Management': 172,
  'IT Support & Administration': 240,
  'UI/UX & Design': 144,
  'Other': 193},
 2021: {'Software Engineering': 1354,
  'Data & Analytics': 154,
  'Infrastructure & Networks': 10,
  'Cloud & DevOps': 120,
  'Cybersecurity': 31,
  'Machine Learning & AI': 101,
  'Product & Project Management': 250,
  'IT Support & Administration': 354,
  'UI/UX & Design': 201,
  'Other': 208},
 2019: {'Software Engineering': 804,
  'Data & Analytics': 95,
  'Infrastructure & Networks': 7,
  'Cloud & DevOps': 77,
  'Cybersecurity': 27,
  'Machine Learning & AI': 47,
  'Product & Project Management': 175,
  'IT Support & Administration': 287,
  'UI/UX & Design': 145,
  'Other': 159},
 2020: {'Software Engineering': 1057,
  'Data & Analytics': 129,
  'Infrastructure & Networks': 7,
  'Cloud & DevOps': 89,
  'Cybersecurity': 31,
  'Machine Learning & AI': 68,
  'Product & Project Management': 201,
  'IT Support & Administration': 324,
  'UI/UX & Design': 193,
  'Other': 180},
 2017: {'Software Engineering': 495,
  'Data & Analytics': 45,
  'Infrastructure & Networks': 3,
  'Cloud & DevOps': 43,
  'Cybersecurity': 13,
  'Machine Learning & AI': 20,
  'Product & Project Management': 133,
  'IT Support & Administration': 229,
  'UI/UX & Design': 93,
  'Other': 112},
 2018: {'Software Engineering': 620,
  'Data & Analytics': 69,
  'Infrastructure & Networks': 3,
  'Cloud & DevOps': 65,
  'Cybersecurity': 22,
  'Machine Learning & AI': 35,
  'Product & Project Management': 153,
  'IT Support & Administration': 243,
  'UI/UX & Design': 108,
  'Other': 132}}

In [ ]:
# Store data to json
with open("professions.json", "w", encoding='utf-8') as f:
    json.dump(professions, f, indent=4)

## Chart for skills analysis

In [ ]:
users['skills'][0]

"['JavaScript', 'Liquibase Community Edition', 'SQL', 'REST APIs', 'Git', 'Java', 'Spring Framework', 'PostgreSQL', 'Hibernate', 'Docker Products', 'Swagger API', 'Apache Kafka', 'RabbitMQ', 'Java Database Connectivity (JDBC)', 'Liquibase', 'Spring Boot', 'Spring MVC', 'Maven', 'Gradle', 'Foreign Languages', 'Technical Translation', 'Translation', 'Machine Design', 'Engineering Drawings', 'Software Engineering', 'Structural Calculations', 'Financial Calculations', 'Electrical Machines', 'Vibration Control', 'Machine Tools', 'Language Teaching', 'Social Skills']"

In [ ]:
# Create list for users experiences
users_skills = []

# Go through users['experiences'] to convert it in proper format
for skills in users['skills']:
    # If experience is empty, then skip it
    if len(skills) == 0:
        users_skills.append([])
        continue
    # Convert the string to a list
    data_list = ast.literal_eval(skills)
    users_skills.append(data_list)

In [ ]:
skills_dict = {"Software Engineering": {},
          "Data & Analytics": {},
          "Infrastructure & Networks": {},
          "Cloud & DevOps": {},
          "Cybersecurity": {},
          "Machine Learning & AI": {},
          "Product & Project Management": {},
          "IT Support & Administration": {},
          "UI/UX & Design": {},
          "Other": {}}

In [ ]:
# Iterate over users_skills
for index, user_skills in tqdm(enumerate(users_skills), total=users.shape[0]):
    categories = set()

    # For each user obtain only unique job categories
    for experience in users_experiences[index]:
        category = job_categories_map[experience['title']]
        categories.add(category)

    # For obtained categories calculate for each skill number of people
    for category in list(categories):
        for skill in user_skills:
            if skill == 'Python (Programming Language)':
                skill = "Python"
            if skill == 'Natural Language Processing (NLP)':
                skill = "NLP"
            skills_dict[category][skill] = 1 + skills_dict[category].get(skill, 0)

100%|██████████| 2141/2141 [00:00<00:00, 35955.69it/s]

In [ ]:
top_skills = {}

for category, skills in skills_dict.items():
    # Sort the skills by value (descending) and take the top 10
    sorted_skills = dict(sorted(skills.items(), key=lambda item: item[1], reverse=True)[:10])
    top_skills[category] = sorted_skills

In [ ]:
top_skills

{'Software Engineering': {'Python': 742,
  'Git': 466,
  'SQL': 440,
  'Java': 421,
  'JavaScript': 332,
  'C++': 329,
  'PostgreSQL': 316,
  'Linux': 276,
  'Docker': 224,
  'Machine Learning': 221},
 'Data & Analytics': {'Python': 199,
  'SQL': 112,
  'Machine Learning': 97,
  'Git': 67,
  'Data Analysis': 59,
  'Java': 56,
  'PyTorch': 54,
  'C++': 54,
  'Data Science': 50,
  'Deep Learning': 49},
 'Infrastructure & Networks': {'Python': 22,
  'SQL': 12,
  'Machine Learning': 11,
  'Linux': 10,
  'Deep Learning': 10,
  'C++': 10,
  'Git': 8,
  'PyTorch': 7,
  'Java': 6,
  'Software Development': 6},
 'Cloud & DevOps': {'Python': 136,
  'Git': 84,
  'JavaScript': 83,
  'SQL': 79,
  'Java': 68,
  'PostgreSQL': 68,
  'C++': 57,
  'Project Management': 54,
  'Linux': 52,
  'Docker': 50},
 'Cybersecurity': {'Python': 48,
  'Java': 26,
  'SQL': 26,
  'Linux': 24,
  'Project Management': 24,
  'C++': 21,
  'Software Development': 20,
  'PostgreSQL': 18,
  'Leadership': 18,
  'Machine Learning': 17},
 'Machine Learning & AI': {'Python': 193,
  'Machine Learning': 105,
  'C++': 82,
  'PyTorch': 82,
  'SQL': 77,
  'Java': 72,
  'Computer Vision': 69,
  'Git': 67,
  'Deep Learning': 65,
  'Linux': 55},
 'Product & Project Management': {'Python': 159,
  'SQL': 114,
  'Project Management': 114,
  'Management': 82,
  'Java': 74,
  'Git': 69,
  'C++': 64,
  'Linux': 60,
  'Communication': 59,
  'Team Leadership': 58},
 'IT Support & Administration': {'Python': 334,
  'SQL': 196,
  'Java': 184,
  'Git': 180,
  'C++': 153,
  'Project Management': 134,
  'Linux': 121,
  'JavaScript': 120,
  'Machine Learning': 118,
  'PostgreSQL': 106},
 'UI/UX & Design': {'Python': 184,
  'Git': 106,
  'C++': 98,
  'Java': 95,
  'SQL': 92,
  'JavaScript': 77,
  'Linux': 71,
  'Software Development': 65,
  'C#': 61,
  'Machine Learning': 57},
 'Other': {'Python': 198,
  'SQL': 105,
  'C++': 102,
  'Java': 92,
  'Git': 89,
  'Machine Learning': 73,
  'Linux': 71,
  'JavaScript': 70,
  'Project Management': 68,
  'Software Development': 68}}

In [ ]:
# Build the final JSON structure
output = {
    "professions": []
}

for category, skills in top_skills.items():
    # Format for JSON structure
    profession_entry = {
        "profession_name": category,
        "top_skills": [
            {
                "skill_name": skill,
                "number_of_professionals": count
            } for skill, count in skills.items()
        ]
    }

    output["professions"].append(profession_entry)

In [ ]:
output

{'professions': [{'profession_name': 'Software Engineering',
   'top_skills': [{'skill_name': 'Python', 'number_of_professionals': 742},
    {'skill_name': 'Git', 'number_of_professionals': 466},
    {'skill_name': 'SQL', 'number_of_professionals': 440},
    {'skill_name': 'Java', 'number_of_professionals': 421},
    {'skill_name': 'JavaScript', 'number_of_professionals': 332},
    {'skill_name': 'C++', 'number_of_professionals': 329},
    {'skill_name': 'PostgreSQL', 'number_of_professionals': 316},
    {'skill_name': 'Linux', 'number_of_professionals': 276},
    {'skill_name': 'Docker', 'number_of_professionals': 224},
    {'skill_name': 'Machine Learning', 'number_of_professionals': 221}]},
  {'profession_name': 'Data & Analytics',
   'top_skills': [{'skill_name': 'Python', 'number_of_professionals': 199},
    {'skill_name': 'SQL', 'number_of_professionals': 112},
    {'skill_name': 'Machine Learning', 'number_of_professionals': 97},
    {'skill_name': 'Git', 'number_of_professionals': 67},
    {'skill_name': 'Data Analysis', 'number_of_professionals': 59},
    {'skill_name': 'Java', 'number_of_professionals': 56},
    {'skill_name': 'PyTorch', 'number_of_professionals': 54},
    {'skill_name': 'C++', 'number_of_professionals': 54},
    {'skill_name': 'Data Science', 'number_of_professionals': 50},
    {'skill_name': 'Deep Learning', 'number_of_professionals': 49}]},
  {'profession_name': 'Infrastructure & Networks',
   'top_skills': [{'skill_name': 'Python', 'number_of_professionals': 22},
    {'skill_name': 'SQL', 'number_of_professionals': 12},
    {'skill_name': 'Machine Learning', 'number_of_professionals': 11},
    {'skill_name': 'Linux', 'number_of_professionals': 10},
    {'skill_name': 'Deep Learning', 'number_of_professionals': 10},
    {'skill_name': 'C++', 'number_of_professionals': 10},
    {'skill_name': 'Git', 'number_of_professionals': 8},
    {'skill_name': 'PyTorch', 'number_of_professionals': 7},
    {'skill_name': 'Java', 'number_of_professionals': 6},
    {'skill_name': 'Software Development', 'number_of_professionals': 6}]},
  {'profession_name': 'Cloud & DevOps',
   'top_skills': [{'skill_name': 'Python', 'number_of_professionals': 136},
    {'skill_name': 'Git', 'number_of_professionals': 84},
    {'skill_name': 'JavaScript', 'number_of_professionals': 83},
    {'skill_name': 'SQL', 'number_of_professionals': 79},
    {'skill_name': 'Java', 'number_of_professionals': 68},
    {'skill_name': 'PostgreSQL', 'number_of_professionals': 68},
    {'skill_name': 'C++', 'number_of_professionals': 57},
    {'skill_name': 'Project Management', 'number_of_professionals': 54},
    {'skill_name': 'Linux', 'number_of_professionals': 52},
    {'skill_name': 'Docker', 'number_of_professionals': 50}]},
  {'profession_name': 'Cybersecurity',
   'top_skills': [{'skill_name': 'Python', 'number_of_professionals': 48},
    {'skill_name': 'Java', 'number_of_professionals': 26},
    {'skill_name': 'SQL', 'number_of_professionals': 26},
    {'skill_name': 'Linux', 'number_of_professionals': 24},
    {'skill_name': 'Project Management', 'number_of_professionals': 24},
    {'skill_name': 'C++', 'number_of_professionals': 21},
    {'skill_name': 'Software Development', 'number_of_professionals': 20},
    {'skill_name': 'PostgreSQL', 'number_of_professionals': 18},
    {'skill_name': 'Leadership', 'number_of_professionals': 18},
    {'skill_name': 'Machine Learning', 'number_of_professionals': 17}]},
  {'profession_name': 'Machine Learning & AI',
   'top_skills': [{'skill_name': 'Python', 'number_of_professionals': 193},
    {'skill_name': 'Machine Learning', 'number_of_professionals': 105},
    {'skill_name': 'C++', 'number_of_professionals': 82},
    {'skill_name': 'PyTorch', 'number_of_professionals': 82},
    {'skill_name': 'SQL', 'number_of_professionals': 77},
    {'skill_name': 'Java', 'number_of_professionals': 72},
    {'skill_name': 'Computer Vision', 'number_of_professionals': 69},
    {'skill_name': 'Git', 'number_of_professionals': 67},
    {'skill_name': 'Deep Learning', 'number_of_professionals': 65},
    {'skill_name': 'Linux', 'number_of_professionals': 55}]},
  {'profession_name': 'Product & Project Management',
   'top_skills': [{'skill_name': 'Python', 'number_of_professionals': 159},
    {'skill_name': 'SQL', 'number_of_professionals': 114},
    {'skill_name': 'Project Management', 'number_of_professionals': 114},
    {'skill_name': 'Management', 'number_of_professionals': 82},
    {'skill_name': 'Java', 'number_of_professionals': 74},
    {'skill_name': 'Git', 'number_of_professionals': 69},
    {'skill_name': 'C++', 'number_of_professionals': 64},
    {'skill_name': 'Linux', 'number_of_professionals': 60},
    {'skill_name': 'Communication', 'number_of_professionals': 59},
    {'skill_name': 'Team Leadership', 'number_of_professionals': 58}]},
  {'profession_name': 'IT Support & Administration',
   'top_skills': [{'skill_name': 'Python', 'number_of_professionals': 334},
    {'skill_name': 'SQL', 'number_of_professionals': 196},
    {'skill_name': 'Java', 'number_of_professionals': 184},
    {'skill_name': 'Git', 'number_of_professionals': 180},
    {'skill_name': 'C++', 'number_of_professionals': 153},
    {'skill_name': 'Project Management', 'number_of_professionals': 134},
    {'skill_name': 'Linux', 'number_of_professionals': 121},
    {'skill_name': 'JavaScript', 'number_of_professionals': 120},
    {'skill_name': 'Machine Learning', 'number_of_professionals': 118},
    {'skill_name': 'PostgreSQL', 'number_of_professionals': 106}]},
  {'profession_name': 'UI/UX & Design',
   'top_skills': [{'skill_name': 'Python', 'number_of_professionals': 184},
    {'skill_name': 'Git', 'number_of_professionals': 106},
    {'skill_name': 'C++', 'number_of_professionals': 98},
    {'skill_name': 'Java', 'number_of_professionals': 95},
    {'skill_name': 'SQL', 'number_of_professionals': 92},
    {'skill_name': 'JavaScript', 'number_of_professionals': 77},
    {'skill_name': 'Linux', 'number_of_professionals': 71},
    {'skill_name': 'Software Development', 'number_of_professionals': 65},
    {'skill_name': 'C#', 'number_of_professionals': 61},
    {'skill_name': 'Machine Learning', 'number_of_professionals': 57}]},
  {'profession_name': 'Other',
   'top_skills': [{'skill_name': 'Python', 'number_of_professionals': 198},
    {'skill_name': 'SQL', 'number_of_professionals': 105},
    {'skill_name': 'C++', 'number_of_professionals': 102},
    {'skill_name': 'Java', 'number_of_professionals': 92},
    {'skill_name': 'Git', 'number_of_professionals': 89},
    {'skill_name': 'Machine Learning', 'number_of_professionals': 73},
    {'skill_name': 'Linux', 'number_of_professionals': 71},
    {'skill_name': 'JavaScript', 'number_of_professionals': 70},
    {'skill_name': 'Project Management', 'number_of_professionals': 68},
    {'skill_name': 'Software Development', 'number_of_professionals': 68}]}]}

In [ ]:
# Save to JSON file
with open("skills.json", "w", encoding="utf-8") as f:
    json.dump(output, f, indent=4)

## Chart for transitions

In [167]:
from collections import defaultdict

# List of company name keywords to look for (in lowercase)
target_keywords = [
    "yandex", "sber", "tinkoff", "gazprom", "mts", "alfa", "x5", "icl", "ak bars", "akbars", "kazanexpress", "magnit market",
    "kaspersky", "vk", "innopolis university", "tbank", "rostelecom", "ozon"
]

# Initialize counter
company_counts = defaultdict(int)
transactions_start_date = pd.to_datetime(datetime.today())

users_for_company = {}
all_users = set()
dates = []
# Count matches
for index, experiences in enumerate(users_experiences):
    if "innopolis" in users['school_1'][index].lower() or \
    "иннополис" in users['school_1'][index].lower() or \
    "innopolis" in users['school_2'][index].lower() or \
    "иннополис" in users['school_2'][index].lower():
        if not users['estimated_age'][index] or users['estimated_age'][index] <= 35:
            for experience in experiences:
                if not experience['company']:
                    continue
                if not experience['start_date']:
                    continue
                if pd.to_datetime(experience['start_date']) and pd.to_datetime(experience['start_date']).year < 2014:
                    continue
                name = experience['company'].lower()
                dates.append(experience['start_date'])
                for keyword in target_keywords:
                    if keyword in name:
                        company_counts[keyword] += 1
                        if keyword not in users_for_company:
                            users_for_company[keyword] = set()
                        users_for_company[keyword].add(users['id'][index])
                        all_users.add(users['id'][index])

                        if pd.to_datetime(experience['start_date']) and pd.to_datetime(experience['start_date']) < transactions_start_date:
                            transactions_start_date = pd.to_datetime(experience['start_date'])
                        break  # if one match per name is enough

# Display results
for company, count in company_counts.items():
    print(f"{company.title()}: {count}")
print()
# Display results
for company, users_set in users_for_company.items():
    print(f"{company}: {len(users_set)}")

Innopolis University: 398
Ak Bars: 35
Yandex: 194
Sber: 91
X5: 29
Ozon: 42
Icl: 15
Gazprom: 23
Magnit Market: 3
Kazanexpress: 41
Tinkoff: 122
Mts: 76
Vk: 12
Alfa: 7
Rostelecom: 4
Kaspersky: 4
Tbank: 1
Akbars: 1

innopolis university: 257
ak bars: 33
yandex: 138
sber: 78
x5: 26
ozon: 35
icl: 13
gazprom: 19
magnit market: 3
kazanexpress: 29
tinkoff: 90
mts: 62
vk: 11
alfa: 6
rostelecom: 4
kaspersky: 3
tbank: 1
akbars: 1

In [168]:
transactions_start_date

Timestamp('2014-03-14 00:00:00')

In [169]:
len(all_users)

607

In [172]:
# Store info about user work
rows = []

# Mapping keywords with company name
target_keywords_dict = {"yandex": "Yandex",
                        "sber": "Sber",
                        "tinkoff": "TBank",
                        "gazprom": "Gazprom",
                        "mts": "MTS",
                        "alfa": "Alfa",
                        "x5": "X5 Retail Group",
                        "icl": "ICL",
                        "ak bars": "Ak Bars",
                        "akbars": "Ak Bars",
                        "kazanexpress": "Magnit Market",
                        "magnit market": "Magnit Market",
                        "kaspersky": "Kaspersky",
                        "vk": "VK",
                        "innopolis university": "Innopolis University",
                        "tbank": "TBank",
                        "rostelecom": "Rostelecom",
                        "ozon": "Ozon",
                        "other": "Other",
                        "not working": "Not Working"
                        }

all_users = list(all_users)

# Iterate over user IDs
for user_id in tqdm(all_users):
    # Obtain user_experiences using index from ID
    user_experiences = users_experiences[users[users['id'] == user_id].index[0]]
    # Create variable to catch case then end date is none, however it is not last user work
    potential_end_date = None
    # Save order of works
    work_counter = 0
    for experience in user_experiences:
        if not experience['company']:
            continue
        if not experience['start_date']:
            continue
        if pd.to_datetime(experience['start_date']) and pd.to_datetime(experience['start_date']).year < 2014:
            continue

        name = experience['company'].lower()

        # Create default dict with user info
        new_row = {'pid': user_id,
                   'grp': target_keywords_dict["other"],
                   'work_counter': work_counter,
                   'duration': 0,
                   'name': users[users['id'] == user_id]['name'].values[0],
                   'location': users[users['id'] == user_id]['location'].values[0],
                   'estimated_age': users[users['id'] == user_id]['estimated_age'].values[0],
                   'start_date': pd.to_datetime(experience['start_date']),
                   'end_date': pd.to_datetime(experience['end_date']) if experience['end_date'] else potential_end_date,
                   'job_position': experience['title'],
                   'company_name': experience['company']
                   }

        # Save start time
        potential_end_date = pd.to_datetime(experience['start_date'])

        # Change grp info if work from our considered companies
        for keyword in target_keywords_dict.keys():
            if keyword in name:
                new_row['grp'] = target_keywords_dict[keyword]
                break
        # Consider case when user change the work place and did not work sometime
        if len(rows) != 0 and rows[-1]['pid'] == new_row['pid']:
            if rows[-1]['start_date'] > new_row['end_date']:
                # Save "not working" case
                not_work_row = {'pid': user_id,
                                'grp': target_keywords_dict["not working"],
                                'work_counter': work_counter,
                                'duration': 0,
                                'name': users[users['id'] == user_id]['name'].values[0],
                                'location': users[users['id'] == user_id]['location'].values[0],
                                'estimated_age': users[users['id'] == user_id]['estimated_age'].values[0],
                                'start_date': new_row['end_date'],
                                'end_date': rows[-1]['start_date'],
                                'job_position': None,
                                'company_name': None
                                }
                work_counter += 1
                new_row['work_counter'] = work_counter
                rows.append(not_work_row)
        work_counter += 1
        rows.append(new_row)

# Create dataframe using work info
transitions = pd.DataFrame(rows)

100%|██████████| 607/607 [00:15<00:00, 38.54it/s]

In [173]:
transitions

,pid,grp,work_counter,duration,name,location,estimated_age,start_date,end_date,job_position,company_name
0,ACoAAD1cxHkBeSUsVMJC9J0GalwGuCTLDzWKg44,Other,0,0,Amine Trabelsi,"Innopolis, Tatarstan, Russia",21.0,2024-11-23,NaT,Research Assistant,Q Deep
1,ACoAAD1cxHkBeSUsVMJC9J0GalwGuCTLDzWKg44,Innopolis University,1,0,Amine Trabelsi,"Innopolis, Tatarstan, Russia",21.0,2022-09-23,2024-11-23,Student,Innopolis University
2,ACoAAB0G5MgBIfIXc2PapACNaUzGQXdhujXH9yo,Other,0,0,Oleg Taizov,"Moscow, Moscow City, Russia",27.0,2024-04-06,NaT,Engineering Manager,Uzum
3,ACoAAB0G5MgBIfIXc2PapACNaUzGQXdhujXH9yo,Magnit Market,1,0,Oleg Taizov,"Moscow, Moscow City, Russia",27.0,2019-05-06,2024-07-06,Backend & Data engineer,Marketplais KazAnexpress
4,ACoAAB2s9mkBsPRzg3ZBBhe1pbo1Djd4bQ7fBPM,Innopolis University,0,0,Ahmed Nouralla,"Innopolis, Tatarstan, Russia",23.0,2025-01-06,NaT,Teaching Assistant,Innopolis University
...,...,...,...,...,...,...,...,...,...,...,...
3897,ACoAABwIs7gBwRfxdXhdYe6Kqp5H8eyZ7pofFDg,Other,2,0,Ekaterina L.,"Berlin, Berlin, Germany",27.0,2021-05-14,2021-11-14,Android Engineer,Soramitsu Сорамитсу
3898,ACoAABwIs7gBwRfxdXhdYe6Kqp5H8eyZ7pofFDg,Not Working,3,0,Ekaterina L.,"Berlin, Berlin, Germany",27.0,2021-04-14,2021-05-14,None,None
3899,ACoAABwIs7gBwRfxdXhdYe6Kqp5H8eyZ7pofFDg,X5 Retail Group,4,0,Ekaterina L.,"Berlin, Berlin, Germany",27.0,2020-03-14,2021-04-14,Middle Android Developer,X5 Retail Group
3900,ACoAABwIs7gBwRfxdXhdYe6Kqp5H8eyZ7pofFDg,Not Working,5,0,Ekaterina L.,"Berlin, Berlin, Germany",27.0,2019-11-14,2020-03-14,None,None
3901,ACoAABwIs7gBwRfxdXhdYe6Kqp5H8eyZ7pofFDg,Other,6,0,Ekaterina L.,"Berlin, Berlin, Germany",27.0,2019-09-14,2019-11-14,Python developer,Siemens R&D

In [174]:
def calculate_duration(row):
    if pd.isna(row['end_date']):
        return -99
    months = (row['end_date'].year - row['start_date'].year) * 12 + (row['end_date'].month - row['start_date'].month)

    # Consider partial months
    if row['end_date'].day < row['start_date'].day:
        months -= 1
    return months

# Calculate the duration of work in months
transitions['duration'] = transitions.apply(calculate_duration, axis=1)

In [175]:
transitions

,pid,grp,work_counter,duration,name,location,estimated_age,start_date,end_date,job_position,company_name
0,ACoAAD1cxHkBeSUsVMJC9J0GalwGuCTLDzWKg44,Other,0,-99,Amine Trabelsi,"Innopolis, Tatarstan, Russia",21.0,2024-11-23,NaT,Research Assistant,Q Deep
1,ACoAAD1cxHkBeSUsVMJC9J0GalwGuCTLDzWKg44,Innopolis University,1,26,Amine Trabelsi,"Innopolis, Tatarstan, Russia",21.0,2022-09-23,2024-11-23,Student,Innopolis University
2,ACoAAB0G5MgBIfIXc2PapACNaUzGQXdhujXH9yo,Other,0,-99,Oleg Taizov,"Moscow, Moscow City, Russia",27.0,2024-04-06,NaT,Engineering Manager,Uzum
3,ACoAAB0G5MgBIfIXc2PapACNaUzGQXdhujXH9yo,Magnit Market,1,62,Oleg Taizov,"Moscow, Moscow City, Russia",27.0,2019-05-06,2024-07-06,Backend & Data engineer,Marketplais KazAnexpress
4,ACoAAB2s9mkBsPRzg3ZBBhe1pbo1Djd4bQ7fBPM,Innopolis University,0,-99,Ahmed Nouralla,"Innopolis, Tatarstan, Russia",23.0,2025-01-06,NaT,Teaching Assistant,Innopolis University
...,...,...,...,...,...,...,...,...,...,...,...
3897,ACoAABwIs7gBwRfxdXhdYe6Kqp5H8eyZ7pofFDg,Other,2,6,Ekaterina L.,"Berlin, Berlin, Germany",27.0,2021-05-14,2021-11-14,Android Engineer,Soramitsu Сорамитсу
3898,ACoAABwIs7gBwRfxdXhdYe6Kqp5H8eyZ7pofFDg,Not Working,3,1,Ekaterina L.,"Berlin, Berlin, Germany",27.0,2021-04-14,2021-05-14,None,None
3899,ACoAABwIs7gBwRfxdXhdYe6Kqp5H8eyZ7pofFDg,X5 Retail Group,4,13,Ekaterina L.,"Berlin, Berlin, Germany",27.0,2020-03-14,2021-04-14,Middle Android Developer,X5 Retail Group
3900,ACoAABwIs7gBwRfxdXhdYe6Kqp5H8eyZ7pofFDg,Not Working,5,4,Ekaterina L.,"Berlin, Berlin, Germany",27.0,2019-11-14,2020-03-14,None,None
3901,ACoAABwIs7gBwRfxdXhdYe6Kqp5H8eyZ7pofFDg,Other,6,2,Ekaterina L.,"Berlin, Berlin, Germany",27.0,2019-09-14,2019-11-14,Python developer,Siemens R&D

In [176]:
def reverse_work_counter(row):
    total = transitions[transitions["pid"] == row["pid"]]["pid"].count()
    return total - row["work_counter"]

In [177]:
# Reverse the work order
transitions['work_counter'] = transitions.apply(reverse_work_counter, axis=1)

In [178]:
transitions

,pid,grp,work_counter,duration,name,location,estimated_age,start_date,end_date,job_position,company_name
0,ACoAAD1cxHkBeSUsVMJC9J0GalwGuCTLDzWKg44,Other,2,-99,Amine Trabelsi,"Innopolis, Tatarstan, Russia",21.0,2024-11-23,NaT,Research Assistant,Q Deep
1,ACoAAD1cxHkBeSUsVMJC9J0GalwGuCTLDzWKg44,Innopolis University,1,26,Amine Trabelsi,"Innopolis, Tatarstan, Russia",21.0,2022-09-23,2024-11-23,Student,Innopolis University
2,ACoAAB0G5MgBIfIXc2PapACNaUzGQXdhujXH9yo,Other,2,-99,Oleg Taizov,"Moscow, Moscow City, Russia",27.0,2024-04-06,NaT,Engineering Manager,Uzum
3,ACoAAB0G5MgBIfIXc2PapACNaUzGQXdhujXH9yo,Magnit Market,1,62,Oleg Taizov,"Moscow, Moscow City, Russia",27.0,2019-05-06,2024-07-06,Backend & Data engineer,Marketplais KazAnexpress
4,ACoAAB2s9mkBsPRzg3ZBBhe1pbo1Djd4bQ7fBPM,Innopolis University,12,-99,Ahmed Nouralla,"Innopolis, Tatarstan, Russia",23.0,2025-01-06,NaT,Teaching Assistant,Innopolis University
...,...,...,...,...,...,...,...,...,...,...,...
3897,ACoAABwIs7gBwRfxdXhdYe6Kqp5H8eyZ7pofFDg,Other,5,6,Ekaterina L.,"Berlin, Berlin, Germany",27.0,2021-05-14,2021-11-14,Android Engineer,Soramitsu Сорамитсу
3898,ACoAABwIs7gBwRfxdXhdYe6Kqp5H8eyZ7pofFDg,Not Working,4,1,Ekaterina L.,"Berlin, Berlin, Germany",27.0,2021-04-14,2021-05-14,None,None
3899,ACoAABwIs7gBwRfxdXhdYe6Kqp5H8eyZ7pofFDg,X5 Retail Group,3,13,Ekaterina L.,"Berlin, Berlin, Germany",27.0,2020-03-14,2021-04-14,Middle Android Developer,X5 Retail Group
3900,ACoAABwIs7gBwRfxdXhdYe6Kqp5H8eyZ7pofFDg,Not Working,2,4,Ekaterina L.,"Berlin, Berlin, Germany",27.0,2019-11-14,2020-03-14,None,None
3901,ACoAABwIs7gBwRfxdXhdYe6Kqp5H8eyZ7pofFDg,Other,1,2,Ekaterina L.,"Berlin, Berlin, Germany",27.0,2019-09-14,2019-11-14,Python developer,Siemens R&D

In [179]:
min_date = transitions['start_date'].min()
# max_date = transitions['end_date'].max()
print(min_date)

2014-01-06 00:00:00

In [180]:
index = 0

# Normalize all users by 2013-12-31 date
while index < transitions.shape[0]:
    if transitions['work_counter'][index] == 1:
        duration = (transitions['start_date'][index].year - pd.to_datetime("2013-12-31").year) * 12 + (transitions['start_date'][index].month - pd.to_datetime("2013-12-31").month)
        new_row = pd.DataFrame([{'pid': transitions['pid'][index],
                   'grp': target_keywords_dict["not working"],
                   'work_counter': 0,
                   'duration': duration,
                   'name': transitions['name'][index],
                   'location': transitions['location'][index],
                   'estimated_age': transitions['estimated_age'][index],
                   'start_date': None,
                   'end_date': None,
                   'job_position': None,
                   'company_name': None
                   }])
        index += 1
        transitions = pd.concat([transitions.iloc[:index], new_row, transitions.iloc[index:]]).reset_index(drop=True)

    index += 1

<ipython-input-180-6d0e36741c55>:20: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  transitions = pd.concat([transitions.iloc[:index], new_row, transitions.iloc[index:]]).reset_index(drop=True)

In [181]:
transitions

,pid,grp,work_counter,duration,name,location,estimated_age,start_date,end_date,job_position,company_name
0,ACoAAD1cxHkBeSUsVMJC9J0GalwGuCTLDzWKg44,Other,2,-99,Amine Trabelsi,"Innopolis, Tatarstan, Russia",21.0,2024-11-23,NaT,Research Assistant,Q Deep
1,ACoAAD1cxHkBeSUsVMJC9J0GalwGuCTLDzWKg44,Innopolis University,1,26,Amine Trabelsi,"Innopolis, Tatarstan, Russia",21.0,2022-09-23,2024-11-23,Student,Innopolis University
2,ACoAAD1cxHkBeSUsVMJC9J0GalwGuCTLDzWKg44,Not Working,0,105,Amine Trabelsi,"Innopolis, Tatarstan, Russia",21.0,NaT,NaT,None,None
3,ACoAAB0G5MgBIfIXc2PapACNaUzGQXdhujXH9yo,Other,2,-99,Oleg Taizov,"Moscow, Moscow City, Russia",27.0,2024-04-06,NaT,Engineering Manager,Uzum
4,ACoAAB0G5MgBIfIXc2PapACNaUzGQXdhujXH9yo,Magnit Market,1,62,Oleg Taizov,"Moscow, Moscow City, Russia",27.0,2019-05-06,2024-07-06,Backend & Data engineer,Marketplais KazAnexpress
...,...,...,...,...,...,...,...,...,...,...,...
4504,ACoAABwIs7gBwRfxdXhdYe6Kqp5H8eyZ7pofFDg,Not Working,4,1,Ekaterina L.,"Berlin, Berlin, Germany",27.0,2021-04-14,2021-05-14,None,None
4505,ACoAABwIs7gBwRfxdXhdYe6Kqp5H8eyZ7pofFDg,X5 Retail Group,3,13,Ekaterina L.,"Berlin, Berlin, Germany",27.0,2020-03-14,2021-04-14,Middle Android Developer,X5 Retail Group
4506,ACoAABwIs7gBwRfxdXhdYe6Kqp5H8eyZ7pofFDg,Not Working,2,4,Ekaterina L.,"Berlin, Berlin, Germany",27.0,2019-11-14,2020-03-14,None,None
4507,ACoAABwIs7gBwRfxdXhdYe6Kqp5H8eyZ7pofFDg,Other,1,2,Ekaterina L.,"Berlin, Berlin, Germany",27.0,2019-09-14,2019-11-14,Python developer,Siemens R&D
4508,ACoAABwIs7gBwRfxdXhdYe6Kqp5H8eyZ7pofFDg,Not Working,0,69,Ekaterina L.,"Berlin, Berlin, Germany",27.0,NaT,NaT,None,None

In [182]:
transitions.drop(columns=['start_date', 'end_date'], inplace=True)

In [183]:
transitions

,pid,grp,work_counter,duration,name,location,estimated_age,job_position,company_name
0,ACoAAD1cxHkBeSUsVMJC9J0GalwGuCTLDzWKg44,Other,2,-99,Amine Trabelsi,"Innopolis, Tatarstan, Russia",21.0,Research Assistant,Q Deep
1,ACoAAD1cxHkBeSUsVMJC9J0GalwGuCTLDzWKg44,Innopolis University,1,26,Amine Trabelsi,"Innopolis, Tatarstan, Russia",21.0,Student,Innopolis University
2,ACoAAD1cxHkBeSUsVMJC9J0GalwGuCTLDzWKg44,Not Working,0,105,Amine Trabelsi,"Innopolis, Tatarstan, Russia",21.0,None,None
3,ACoAAB0G5MgBIfIXc2PapACNaUzGQXdhujXH9yo,Other,2,-99,Oleg Taizov,"Moscow, Moscow City, Russia",27.0,Engineering Manager,Uzum
4,ACoAAB0G5MgBIfIXc2PapACNaUzGQXdhujXH9yo,Magnit Market,1,62,Oleg Taizov,"Moscow, Moscow City, Russia",27.0,Backend & Data engineer,Marketplais KazAnexpress
...,...,...,...,...,...,...,...,...,...
4504,ACoAABwIs7gBwRfxdXhdYe6Kqp5H8eyZ7pofFDg,Not Working,4,1,Ekaterina L.,"Berlin, Berlin, Germany",27.0,None,None
4505,ACoAABwIs7gBwRfxdXhdYe6Kqp5H8eyZ7pofFDg,X5 Retail Group,3,13,Ekaterina L.,"Berlin, Berlin, Germany",27.0,Middle Android Developer,X5 Retail Group
4506,ACoAABwIs7gBwRfxdXhdYe6Kqp5H8eyZ7pofFDg,Not Working,2,4,Ekaterina L.,"Berlin, Berlin, Germany",27.0,None,None
4507,ACoAABwIs7gBwRfxdXhdYe6Kqp5H8eyZ7pofFDg,Other,1,2,Ekaterina L.,"Berlin, Berlin, Germany",27.0,Python developer,Siemens R&D
4508,ACoAABwIs7gBwRfxdXhdYe6Kqp5H8eyZ7pofFDg,Not Working,0,69,Ekaterina L.,"Berlin, Berlin, Germany",27.0,None,None

In [184]:
transitions = transitions.iloc[::-1].reset_index(drop=True)

In [185]:
transitions

,pid,grp,work_counter,duration,name,location,estimated_age,job_position,company_name
0,ACoAABwIs7gBwRfxdXhdYe6Kqp5H8eyZ7pofFDg,Not Working,0,69,Ekaterina L.,"Berlin, Berlin, Germany",27.0,None,None
1,ACoAABwIs7gBwRfxdXhdYe6Kqp5H8eyZ7pofFDg,Other,1,2,Ekaterina L.,"Berlin, Berlin, Germany",27.0,Python developer,Siemens R&D
2,ACoAABwIs7gBwRfxdXhdYe6Kqp5H8eyZ7pofFDg,Not Working,2,4,Ekaterina L.,"Berlin, Berlin, Germany",27.0,None,None
3,ACoAABwIs7gBwRfxdXhdYe6Kqp5H8eyZ7pofFDg,X5 Retail Group,3,13,Ekaterina L.,"Berlin, Berlin, Germany",27.0,Middle Android Developer,X5 Retail Group
4,ACoAABwIs7gBwRfxdXhdYe6Kqp5H8eyZ7pofFDg,Not Working,4,1,Ekaterina L.,"Berlin, Berlin, Germany",27.0,None,None
...,...,...,...,...,...,...,...,...,...
4504,ACoAAB0G5MgBIfIXc2PapACNaUzGQXdhujXH9yo,Magnit Market,1,62,Oleg Taizov,"Moscow, Moscow City, Russia",27.0,Backend & Data engineer,Marketplais KazAnexpress
4505,ACoAAB0G5MgBIfIXc2PapACNaUzGQXdhujXH9yo,Other,2,-99,Oleg Taizov,"Moscow, Moscow City, Russia",27.0,Engineering Manager,Uzum
4506,ACoAAD1cxHkBeSUsVMJC9J0GalwGuCTLDzWKg44,Not Working,0,105,Amine Trabelsi,"Innopolis, Tatarstan, Russia",21.0,None,None
4507,ACoAAD1cxHkBeSUsVMJC9J0GalwGuCTLDzWKg44,Innopolis University,1,26,Amine Trabelsi,"Innopolis, Tatarstan, Russia",21.0,Student,Innopolis University
4508,ACoAAD1cxHkBeSUsVMJC9J0GalwGuCTLDzWKg44,Other,2,-99,Amine Trabelsi,"Innopolis, Tatarstan, Russia",21.0,Research Assistant,Q Deep

In [186]:
# Save to JSON file
transitions.to_json("transitions.json", orient="records", indent=4)